apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- hpa.yaml

namespace: cms-laravel

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
  target:
    kind: Deployment
    name: cms-laravel

configMapGenerator:
- name: cms-config
  behavior: merge
  literals:
  - APP_ENV=production
  - APP_DEBUG=false
  - LOG_LEVEL=warning

images:
- name: ghcr.io/liberusoftware/cms-laravel
  newTag: latest
