name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, pdo, pdo_sqlite, sqlite3, bcmath, gd, zip, intl
        coverage: xdebug

    - name: Copy environment file
      run: cp .env.example .env
      
    - name: Install dependencies
      run: composer install --no-interaction --prefer-dist
      
    - name: Generate application key
      run: php artisan key:generate
      
    - name: Run tests
      run: vendor/bin/phpunit --coverage-clover=coverage.xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
         token: ${{ secrets.CODECOV_TOKEN }}
         files: ./coverage.xml
         flags: unittests
         name: codecov-umbrella
         fail_ci_if_error: true

